baseURL = "https://backbonecabal.com"
title = "Backbone Cabal"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "Backbone Cabal"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Backbone Cabal " 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "A backbone site is one that we bend over backwards to make delivery of transactions as reliable and fast as possible,. Such capacity currently include very few providers. "

    # The name to display in the copyright section in the footer
    copyrightname = "Backbone Cabal contributors"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = "https:/github.com/backbonecabal"

    # Show the "built on Hugo" disclaimer
    showhugo = 'false'

    # Urls for social networks
    twitter = "https://twitter.com"
    github = "https://github.com"
    gitlab = "https://gitlab.com"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = true

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "YCabal"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = "https:/github.com/backbonecabal"

    # Text to go before copyright information
    prefix = "[See our information](https://github.com/backbonecabal)"

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = "YCabal"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "Dogma"
    name = "Central Dogma"
    url = "/dogma/"       # The path can lead to a content folder too.
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
